# syntax=docker/dockerfile:1

FROM maven:3-eclipse-temurin-17-alpine as build
ENV HOME=/usr/app
RUN mkdir -p $HOME
WORKDIR $HOME
# layer 1 - package project
# any pom changing cause redownloading dependencies
# non-pom changing cause rebuilding project with cached dependencies
ADD . $HOME
RUN --mount=type=cache,target=/root/.m2 mvn -f $HOME/pom.xml clean package

FROM eclipse-temurin:17-jdk-jammy
COPY --from=build /usr/app/target/demo-*.jar /app/demo-app.jar
ENTRYPOINT java -jar /app/demo-app.jar

# build image
# DOCKER_BUILDKIT=1 docker build -f Dockerfile_buildkit_cached --tag demo-app .

# run built container (detached)
# docker run --rm -d -p 8080:8080 --name demo-server demo-app

# stop running container
# docker stop demo-server